export const bankCodeToName: any = {
    '011': 'First Bank of Nigeria',
    '014': 'Mainstreet Bank',
    '023': 'Citibank',
    '030': 'Heritage Bank',
    '032': 'Union Bank Of Nigeria',
    '033': 'United Bank For Africa',
    '035': 'Wema Bank',
    '040': 'Equitorial Trust Bank',
    '044': 'Access Bank',
    '050': 'Ecobank Nigeria',
    '056': 'Oceanic Bank',
    '057': 'Zenith Bank',
    '058': 'Guaranty Trust Bank',
    '063': 'Diamond Bank',
    '068': 'Standard Chartered Bank',
    '070': 'Fidelity Bank',
    '076': 'Polaris Bank',
    '082': 'Keystone Bank',
    '084': 'Enterprise Bank',
    '085': 'First Inland Bank',
    '100': 'Suntrust',
    '101': 'Providus Bank',
    '214': 'First City Monument Bank',
    '215': 'Unity Bank',
    '221': 'Stanbic IBTC Bank',
    '232': 'Sterling Bank',
  };
  